[options]
work_mode = "sys"
library = "GioWin32"
version = "2.0"
min_cfg_version = "2.56"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]
