[files]
extend-exclude = ["auto", "sys", "gobject-sys", "*.svg", "glib/Gir.toml"]

[default.extend-words]
# Ignore false-positives
gir = "gir"
mak = "mak"
anid = "anid"
lamda = "lamda"
inout = "inout"
relm = "relm"
ba = "ba"
ue = "ue"
ot = "ot"
siz = "siz"
vai = "vai"
guid = "guid"
