[workspace]
resolver = "2"

members = [
  "cairo",
  "cairo/sys",
  "gdk-pixbuf",
  "gdk-pixbuf/sys",
  "gio",
  "gio/sys",
  "glib-build-tools",
  "glib",
  "glib/gobject-sys",
  "glib/sys",
  "glib-macros",
  "graphene",
  "graphene/sys",
  "examples",
  "pango",
  "pango/sys",
  "pangocairo",
  "pangocairo/sys",
]

exclude = ["gir", "checker"]

[workspace.package]
homepage = "https://gtk-rs.org/"
authors = ["The gtk-rs Project Developers"]
version = "0.19.0"
repository = "https://github.com/gtk-rs/gtk-rs-core"
license = "MIT"
exclude = [
    "gir-files/*",
]
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
libc = "0.2"
bitflags = "2.4"
thiserror = "1"
gir-format-check = "^0.1"
glib = { path = "glib" }
gio = { path = "gio" }
pango = { path = "pango" }
cairo-rs = { path = "cairo" }
glib-macros = { path = "glib-macros" }

[workspace.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]
