[build-dependencies]
system-deps = "6"

[dependencies]
libc = "0.2"

[dependencies.cairo]
package = "cairo-sys-rs"
path = "../../cairo/sys"
version = "0.17"

[dependencies.glib]
package = "glib-sys"
path = "../../glib/sys"
version = "0.17"

[dependencies.pango]
package = "pango-sys"
path = "../../pango/sys"
version = "0.17"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = ["glib/dox", "pango/dox", "cairo/dox"]

[lib]
name = "pango_cairo_sys"

[package]
authors = ["The gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtk-3"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
name = "pangocairo-sys"
repository = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.17.2"
edition = "2021"
rust-version = "1.64"

[package.metadata.docs.rs]
features = ["dox"]

[package.metadata.system-deps.pangocairo]
name = "pangocairo"
version = "1.40"
