[options]
girs_directories = ["../gir-files"]
library = "GioWin32"
version = "2.0"
min_cfg_version = "2.56"
use_gi_docgen = true
target_path = "."
work_mode = "normal"
single_version_file = true
deprecate_by_min_version = true
trust_return_value_nullability = true

generate = [
    #"GioWin32.NetworkMonitor",
]

ignore = [
]

manual = [
    "Gio.InputStream",
    "Gio.OutputStream",
    "Gio.SettingsBackend",
]

[[object]]
name = "GioWin32.*"
status = "generate"

[[object]]
name = "GioWin32.InputStream"
status = "generate"
manual_traits = ["InputStreamExtManual"]
    [[object.function]]
    name = "new"
    manual = true
    [[object.function]]
    name = "set_close_handle"
    unsafe = true
    [[object.function]]
    name = "get_handle"
    manual = true

[[object]]
name = "GioWin32.OutputStream"
status = "generate"
manual_traits = ["OutputStreamExtManual"]
    [[object.function]]
    name = "new"
    manual = true
    [[object.function]]
    name = "set_close_handle"
    unsafe = true
    [[object.function]]
    name = "get_handle"
    manual = true
