[options]
girs_directories = ["../gir-files"]
library = "GioWin32"
version = "2.0"
min_cfg_version = "2.56"
use_gi_docgen = true
target_path = "."
work_mode = "normal"
single_version_file = true
deprecate_by_min_version = true
trust_return_value_nullability = true

generate = [
    "GioWin32.InputStream",
    "GioWin32.OutputStream"
    #"GioWin32.NetworkMonitor",
]

ignore = [
]

manual = [
    "Gio.InputStream",
    "Gio.OutputStream",
    "Gio.SettingsBackend",
]

[[object]]
name = "GioWin32.*"
status = "generate"
