[options]
work_mode = "sys"
library = "GLibUnix"
version = "2.0"
min_cfg_version = "2.56"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
]

[[object]]
name = "GLibUnix.*"
status = "generate"
    [[object.function]]
    name = "open_pipe"
    manual = true # different fds annotations 