[options]
work_mode = "sys"
library = "GioUnix"
version = "2.0"
min_cfg_version = "2.56"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
]

[[object]]
name = "GioUnix.MountEntry"
status = "generate"
    [[object.function]]
    name = "copy"
    manual = true # Manual due to mutability issue


[[object]]
name = "GioUnix.MountPoint"
status = "generate"
    [[object.function]]
    name = "copy"
    manual = true # Manual due to mutability issue