[package]
name = "pangocairo"
documentation = "https://gtk-rs.org/gtk-rs-core/stable/latest/docs/pangocairo/"
homepage = "https://gtk-rs.org/"
authors = ["The gtk-rs Project Developers"]
keywords = ["pango", "cairo", "gtk-rs", "gnome"]
readme = "README.md"
version = "0.16.2"
description = "Rust bindings for the PangoCairo library"
repository = "https://github.com/gtk-rs/gtk-rs-core"
license = "MIT"
exclude = [
    "gir-files/*",
]
edition = "2021"
rust-version = "1.63"

[features]
dox = ["glib/dox", "pango/dox", "cairo-rs/dox", "ffi/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
ffi = { version = "0.16", package = "pangocairo-sys", path = "sys" }
glib = { version = "0.16", path = "../glib" }
pango = { version = "0.16", path = "../pango" }
cairo-rs = { version = "0.16", path = "../cairo" }

[dev-dependencies]
gir-format-check = "^0.1"
